- Boogimarket/app/src/main/res/values/strings.xml
> string.xml 수정

- Boogimarket/app/src/main/res/drawable/ic_baseline_chat_24.xml
- Boogimarket/app/src/main/res/drawable/ic_baseline_home_24.xml
- Boogimarket/app/src/main/res/drawable/ic_baseline_person_pin_24.xml
> add drawalvle

- Boogimarket/app/src/main/java/com/example/boogimarket/LoginActivity.kt
- Boogimarket/app/src/main/java/com/example/boogimarket/MainActivity.kt
- Boogimarket/app/src/main/res/layout/activity_login.xml
- Boogimarket/app/src/main/res/layout/activity_register.xml
> register xml 생성

- Boogimarket/app/src/main/AndroidManifest.xml
- Boogimarket/app/src/main/java/com/example/boogimarket/LoginActivity.kt
- Boogimarket/app/src/main/java/com/example/boogimarket/RegisterActivity.kt
- Boogimarket/app/src/main/res/layout/activity_register.xml
AndroidManifest.xml 수정(로그인, 회원가입 액티비티 실행)
파이어베이스 인증하고 이메일과 비밀번호로 로그인하기
이름, 생년월일, 이메일, 비밀번호로 회원가입하고 파이어베이스에 정보 저장
> 로그인, 회원가입 액티비티

- Boogimarket/app/build.gradle
- Boogimarket/app/src/main/java/com/example/boogimarket/LoginActivity.kt
- Boogimarket/app/src/main/java/com/example/boogimarket/RegisterActivity.kt
- Boogimarket/app/src/main/java/com/example/boogimarket/User.kt
- Boogimarket/app/src/main/res/layout/activity_login.xml
- Boogimarket/app/src/main/res/layout/activity_register.xml
- Boogimarket/app/src/main/res/values/themes.xml
실시간 db 저장할 수 있게 수정
UserAdapter에서 userId 오류가 떠서 일단 User 데이터 클래스의 uId를 userId로 바꿈 나중에 원인 알아보고 바꿔야할 것 같음
그리고 회원정보 등록, 로그인 다 가능  하지만 회원가입 하고 파이어베이스에서 realtime database를 들어가면 user가 안나옴
> 로그인, 회원가입 액티비티 수정

- Boogimarket/app/src/main/AndroidManifest.xml
- Boogimarket/app/src/main/java/com/example/boogimarket/LoginActivity.kt
- Boogimarket/app/src/main/java/com/example/boogimarket/RegisterActivity.kt
AndroidManifest.xml 회원가입액티비티 기능 추가
회원가입 액티비티에 백버튼 추가
> 회원가입 액티비티 백버튼 추가

- Boogimarket/app/build.gradle
- Boogimarket/app/src/main/res/drawable/menu_item_color.xml
Firestore DB gradle 추가
메뉴바 아이콘, 텍스트 색상변경
> Firestore DB gradle 추가와 메뉴바 아이콘, 텍스트 색상변경

- Boogimarket/app/src/main/java/com/example/boogimarket/MyPageActivity.kt
- Boogimarket/app/src/main/res/layout/activity_login.xml
> 로그인 화면 위치 조절, 고쳐야할 내용

- Boogimarket/app/src/main/AndroidManifest.xml
- Boogimarket/app/src/main/java/com/example/boogimarket/MyPageActivity.kt
- Boogimarket/app/src/main/res/layout/activity_mypage.xml
로그아웃과 액션바 코드 수정해봤지만 여전히 안됨,, 내일 다시,,
> MyPage 액티비티 수정

- Boogimarket/app/src/main/java/com/example/boogimarket/ChatFragment.kt
- Boogimarket/app/src/main/java/com/example/boogimarket/Fragments.kt
- Boogimarket/app/src/main/java/com/example/boogimarket/HomeFragment.kt
- Boogimarket/app/src/main/java/com/example/boogimarket/MainActivity.kt
- Boogimarket/app/src/main/java/com/example/boogimarket/MyPageFragment.kt
Fragments.kt에 있던 Fragment Class 분리 후 HomeFragment 수정
> Fragment 클래스 분리 후 수정

- Boogimarket/app/src/main/java/com/example/boogimarket/RegisterActivity.kt
- Boogimarket/app/src/main/res/drawable/ic_baseline_logout_24.xml
- Boogimarket/app/src/main/res/layout/activity_mypage.xml
> 로그아웃 아이콘 수정

- Boogimarket/app/src/main/AndroidManifest.xml
- Boogimarket/app/src/main/java/com/example/boogimarket/ChatFragment.kt
- Boogimarket/app/src/main/java/com/example/boogimarket/DetailsActivity.kt
- Boogimarket/app/src/main/java/com/example/boogimarket/HomeFragment.kt
- Boogimarket/app/src/main/java/com/example/boogimarket/ProductInformation.kt
- Boogimarket/app/src/main/res/layout/activity_chatlist.xml
- Boogimarket/app/src/main/res/layout/activity_detail.xml
detail 액티비티를 만들어서 intent로 데이터 전달
> 아이템 리스뷰 누르면 상세 정보 출력 

- Boogimarket/app/src/main/AndroidManifest.xml
- Boogimarket/app/src/main/java/com/example/boogimarket/ChatActivity.kt
- Boogimarket/app/src/main/java/com/example/boogimarket/ChatFragment.kt
- Boogimarket/app/src/main/java/com/example/boogimarket/DetailsActivity.kt
- Boogimarket/app/src/main/java/com/example/boogimarket/Message.kt
- Boogimarket/app/src/main/java/com/example/boogimarket/MessageAdapter.kt
- Boogimarket/app/src/main/java/com/example/boogimarket/User.kt
- Boogimarket/app/src/main/java/com/example/boogimarket/UserAdapter.kt
- Boogimarket/app/src/main/res/layout/activity_detail.xml
- Boogimarket/app/src/main/res/layout/activity_modify.xml
> 쪽지보내기는 했다..

- Boogimarket/app/build.gradle
- Boogimarket/app/src/main/java/com/example/boogimarket/ChatActivity.kt
- Boogimarket/app/src/main/java/com/example/boogimarket/DetailsActivity.kt
- Boogimarket/app/src/main/java/com/example/boogimarket/HomeFragment.kt
피카소 사용해서 함
그리고 채팅을 저장되는 데이터를 간결하게 바꿨다
> home프래그먼트에 이미지 세팅

- Boogimarket/app/src/main/AndroidManifest.xml
- Boogimarket/app/src/main/java/com/example/boogimarket/DetailsActivity.kt
- Boogimarket/app/src/main/java/com/example/boogimarket/ProductInformation.kt
- Boogimarket/app/src/main/res/layout/activity_detail.xml
> feat. 게시물 삭제

- Boogimarket/app/src/main/java/com/example/boogimarket/DetailsActivity.kt
- Boogimarket/app/src/main/java/com/example/boogimarket/WriteDialog.kt
> feat. 액션바 이름 삭제

- Boogimarket/app/src/main/java/com/example/boogimarket/DetailsActivity.kt
- Boogimarket/app/src/main/java/com/example/boogimarket/WriteDialog.kt
- Boogimarket/app/src/main/res/drawable/baseline_delete_forever_24.xml
- Boogimarket/app/src/main/res/drawable/baseline_edit_24.xml
- Boogimarket/app/src/main/res/layout/activity_detail.xml
본인이 쓴 글만 삭제할 수 있게 수정
버튼 xml 수정
WriteDialog 원상복구
> feat. 게시글 삭제 코드 수정 및 WriteDialog 원상복구

- Boogimarket/app/src/main/java/com/example/boogimarket/HomeFragment.kt
> 판매된 상품 필터도 시간 순으로 게시 구현

- Boogimarket/app/src/main/java/com/example/boogimarket/ChatActivity.kt
- Boogimarket/app/src/main/java/com/example/boogimarket/ChatFragment.kt
- Boogimarket/app/src/main/java/com/example/boogimarket/DetailsActivity.kt
- Boogimarket/app/src/main/java/com/example/boogimarket/HomeFragment.kt
- Boogimarket/app/src/main/java/com/example/boogimarket/MainActivity.kt
- Boogimarket/app/src/main/java/com/example/boogimarket/MessageAdapter.kt
- Boogimarket/app/src/main/java/com/example/boogimarket/ProductInformation.kt
- Boogimarket/app/src/main/res/layout/chatlist_design.xml
주석 언어 통일하게 수정
chatlist_design 폰트 크기가 조금 큰 거 같아서 살짝 줄였습니다
> 주석 정리 & chatlist_design 폰트 크기 수정

- Boogimarket/app/src/main/java/com/example/boogimarket/ChatFragment.kt
- Boogimarket/app/src/main/res/layout/chatlist_design.xml
chatlist_design.xml 크기 살짝 줄이고 ChatFragment.kt에서 RecyclerView 구분선 추가
> chatlist_design.xml 수정

- Boogimarket/app/src/main/java/com/example/boogimarket/MySellActivity.kt
- Boogimarket/app/src/main/res/layout/activity_myselllist.xml
- Boogimarket/app/src/main/res/layout/write_product.xml
> feat. MySellActivity.kt에 백버튼 추가

- Boogimarket/app/src/main/AndroidManifest.xml
- Boogimarket/app/src/main/java/com/example/boogimarket/DetailsActivity.kt
- Boogimarket/app/src/main/res/drawable/ic_baseline_chat_24.xml
- Boogimarket/app/src/main/res/layout/activity_detail.xml
> feat. 백버튼 추가 및 xml ui 고치기
